version: "3.8"
services:
  spring:
    container_name: daumnal-spring
    image: spring-image
    build:
      context: ../../daumnal
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    networks:
      - daumnal-network
    restart: always
  fastapi:
    container_name: daumnal-fastapi
    image: fastapi-image
    build:
      context: ../../fastapi
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    networks:
      - daumnal-network
    restart: always
networks:
  daumnal-network:
    external: true