version: "3.8"
services:
  mysql:
    container_name: daumnal-mysql
    build:
      context: ./db/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
  redis:
    container_name: daumnal-redis
    build:
      context: ./db/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-conf-volume:/usr/local/etc/redis
      - redis-data-volume:/data
    restart: always
  jenkins:
    container_name: daumnal-jenkins
    build:
      context: ./db/jenkins
      dockerfile: Dockerfile
    ports:
      - 8081:8000
      - 50000:50000
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-volume:/var/jenkins_home
    restart: always
  spring:
    container_name: daumnal-spring
    build:
      context: ./daumnal
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    restart: always
  fastapi:
    container_name: daumnal-flask
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
    restart: always
volumes:
  mysql-volume:
    external: true
  redis-conf-volume:
    external: true
  redis-data-volume:
    external: true
  jenkins-volume:
    external: true