version: "3.8"
services:
  spring:
    container_name: daumnal-spring
    build:
      context: ./daumnal
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    restart: always
  fastapi:
    container_name: daumnal-fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
    restart: always
volumes:
  jenkins-volume:
    external: true